// Code generated by ent, DO NOT EDIT.

package record

import (
	"entgo.io/ent/dialect/sql"
	"github.com/GrewalAS/yt-transcription-translation/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldID, id))
}

// VideoURL applies equality check predicate on the "video_url" field. It's identical to VideoURLEQ.
func VideoURL(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldVideoURL, v))
}

// VideoID applies equality check predicate on the "video_id" field. It's identical to VideoIDEQ.
func VideoID(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldVideoID, v))
}

// OriginalLanguage applies equality check predicate on the "original_language" field. It's identical to OriginalLanguageEQ.
func OriginalLanguage(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldOriginalLanguage, v))
}

// FileLocation applies equality check predicate on the "file_location" field. It's identical to FileLocationEQ.
func FileLocation(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldFileLocation, v))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldRunID, v))
}

// Transcript applies equality check predicate on the "transcript" field. It's identical to TranscriptEQ.
func Transcript(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldTranscript, v))
}

// TranslationTargetLanguage applies equality check predicate on the "translation_target_language" field. It's identical to TranslationTargetLanguageEQ.
func TranslationTargetLanguage(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldTranslationTargetLanguage, v))
}

// Translation applies equality check predicate on the "translation" field. It's identical to TranslationEQ.
func Translation(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldTranslation, v))
}

// VideoURLEQ applies the EQ predicate on the "video_url" field.
func VideoURLEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldVideoURL, v))
}

// VideoURLNEQ applies the NEQ predicate on the "video_url" field.
func VideoURLNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldVideoURL, v))
}

// VideoURLIn applies the In predicate on the "video_url" field.
func VideoURLIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldVideoURL, vs...))
}

// VideoURLNotIn applies the NotIn predicate on the "video_url" field.
func VideoURLNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldVideoURL, vs...))
}

// VideoURLGT applies the GT predicate on the "video_url" field.
func VideoURLGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldVideoURL, v))
}

// VideoURLGTE applies the GTE predicate on the "video_url" field.
func VideoURLGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldVideoURL, v))
}

// VideoURLLT applies the LT predicate on the "video_url" field.
func VideoURLLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldVideoURL, v))
}

// VideoURLLTE applies the LTE predicate on the "video_url" field.
func VideoURLLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldVideoURL, v))
}

// VideoURLContains applies the Contains predicate on the "video_url" field.
func VideoURLContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldVideoURL, v))
}

// VideoURLHasPrefix applies the HasPrefix predicate on the "video_url" field.
func VideoURLHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldVideoURL, v))
}

// VideoURLHasSuffix applies the HasSuffix predicate on the "video_url" field.
func VideoURLHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldVideoURL, v))
}

// VideoURLEqualFold applies the EqualFold predicate on the "video_url" field.
func VideoURLEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldVideoURL, v))
}

// VideoURLContainsFold applies the ContainsFold predicate on the "video_url" field.
func VideoURLContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldVideoURL, v))
}

// VideoIDEQ applies the EQ predicate on the "video_id" field.
func VideoIDEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldVideoID, v))
}

// VideoIDNEQ applies the NEQ predicate on the "video_id" field.
func VideoIDNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldVideoID, v))
}

// VideoIDIn applies the In predicate on the "video_id" field.
func VideoIDIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldVideoID, vs...))
}

// VideoIDNotIn applies the NotIn predicate on the "video_id" field.
func VideoIDNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldVideoID, vs...))
}

// VideoIDGT applies the GT predicate on the "video_id" field.
func VideoIDGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldVideoID, v))
}

// VideoIDGTE applies the GTE predicate on the "video_id" field.
func VideoIDGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldVideoID, v))
}

// VideoIDLT applies the LT predicate on the "video_id" field.
func VideoIDLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldVideoID, v))
}

// VideoIDLTE applies the LTE predicate on the "video_id" field.
func VideoIDLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldVideoID, v))
}

// VideoIDContains applies the Contains predicate on the "video_id" field.
func VideoIDContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldVideoID, v))
}

// VideoIDHasPrefix applies the HasPrefix predicate on the "video_id" field.
func VideoIDHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldVideoID, v))
}

// VideoIDHasSuffix applies the HasSuffix predicate on the "video_id" field.
func VideoIDHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldVideoID, v))
}

// VideoIDEqualFold applies the EqualFold predicate on the "video_id" field.
func VideoIDEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldVideoID, v))
}

// VideoIDContainsFold applies the ContainsFold predicate on the "video_id" field.
func VideoIDContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldVideoID, v))
}

// OriginalLanguageEQ applies the EQ predicate on the "original_language" field.
func OriginalLanguageEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldOriginalLanguage, v))
}

// OriginalLanguageNEQ applies the NEQ predicate on the "original_language" field.
func OriginalLanguageNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldOriginalLanguage, v))
}

// OriginalLanguageIn applies the In predicate on the "original_language" field.
func OriginalLanguageIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldOriginalLanguage, vs...))
}

// OriginalLanguageNotIn applies the NotIn predicate on the "original_language" field.
func OriginalLanguageNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldOriginalLanguage, vs...))
}

// OriginalLanguageGT applies the GT predicate on the "original_language" field.
func OriginalLanguageGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldOriginalLanguage, v))
}

// OriginalLanguageGTE applies the GTE predicate on the "original_language" field.
func OriginalLanguageGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldOriginalLanguage, v))
}

// OriginalLanguageLT applies the LT predicate on the "original_language" field.
func OriginalLanguageLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldOriginalLanguage, v))
}

// OriginalLanguageLTE applies the LTE predicate on the "original_language" field.
func OriginalLanguageLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldOriginalLanguage, v))
}

// OriginalLanguageContains applies the Contains predicate on the "original_language" field.
func OriginalLanguageContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldOriginalLanguage, v))
}

// OriginalLanguageHasPrefix applies the HasPrefix predicate on the "original_language" field.
func OriginalLanguageHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldOriginalLanguage, v))
}

// OriginalLanguageHasSuffix applies the HasSuffix predicate on the "original_language" field.
func OriginalLanguageHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldOriginalLanguage, v))
}

// OriginalLanguageEqualFold applies the EqualFold predicate on the "original_language" field.
func OriginalLanguageEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldOriginalLanguage, v))
}

// OriginalLanguageContainsFold applies the ContainsFold predicate on the "original_language" field.
func OriginalLanguageContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldOriginalLanguage, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldStatus, vs...))
}

// FileLocationEQ applies the EQ predicate on the "file_location" field.
func FileLocationEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldFileLocation, v))
}

// FileLocationNEQ applies the NEQ predicate on the "file_location" field.
func FileLocationNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldFileLocation, v))
}

// FileLocationIn applies the In predicate on the "file_location" field.
func FileLocationIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldFileLocation, vs...))
}

// FileLocationNotIn applies the NotIn predicate on the "file_location" field.
func FileLocationNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldFileLocation, vs...))
}

// FileLocationGT applies the GT predicate on the "file_location" field.
func FileLocationGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldFileLocation, v))
}

// FileLocationGTE applies the GTE predicate on the "file_location" field.
func FileLocationGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldFileLocation, v))
}

// FileLocationLT applies the LT predicate on the "file_location" field.
func FileLocationLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldFileLocation, v))
}

// FileLocationLTE applies the LTE predicate on the "file_location" field.
func FileLocationLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldFileLocation, v))
}

// FileLocationContains applies the Contains predicate on the "file_location" field.
func FileLocationContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldFileLocation, v))
}

// FileLocationHasPrefix applies the HasPrefix predicate on the "file_location" field.
func FileLocationHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldFileLocation, v))
}

// FileLocationHasSuffix applies the HasSuffix predicate on the "file_location" field.
func FileLocationHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldFileLocation, v))
}

// FileLocationIsNil applies the IsNil predicate on the "file_location" field.
func FileLocationIsNil() predicate.Record {
	return predicate.Record(sql.FieldIsNull(FieldFileLocation))
}

// FileLocationNotNil applies the NotNil predicate on the "file_location" field.
func FileLocationNotNil() predicate.Record {
	return predicate.Record(sql.FieldNotNull(FieldFileLocation))
}

// FileLocationEqualFold applies the EqualFold predicate on the "file_location" field.
func FileLocationEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldFileLocation, v))
}

// FileLocationContainsFold applies the ContainsFold predicate on the "file_location" field.
func FileLocationContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldFileLocation, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDGT applies the GT predicate on the "run_id" field.
func RunIDGT(v uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldRunID, v))
}

// RunIDGTE applies the GTE predicate on the "run_id" field.
func RunIDGTE(v uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldRunID, v))
}

// RunIDLT applies the LT predicate on the "run_id" field.
func RunIDLT(v uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldRunID, v))
}

// RunIDLTE applies the LTE predicate on the "run_id" field.
func RunIDLTE(v uuid.UUID) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldRunID, v))
}

// RunIDIsNil applies the IsNil predicate on the "run_id" field.
func RunIDIsNil() predicate.Record {
	return predicate.Record(sql.FieldIsNull(FieldRunID))
}

// RunIDNotNil applies the NotNil predicate on the "run_id" field.
func RunIDNotNil() predicate.Record {
	return predicate.Record(sql.FieldNotNull(FieldRunID))
}

// TranscriptEQ applies the EQ predicate on the "transcript" field.
func TranscriptEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldTranscript, v))
}

// TranscriptNEQ applies the NEQ predicate on the "transcript" field.
func TranscriptNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldTranscript, v))
}

// TranscriptIn applies the In predicate on the "transcript" field.
func TranscriptIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldTranscript, vs...))
}

// TranscriptNotIn applies the NotIn predicate on the "transcript" field.
func TranscriptNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldTranscript, vs...))
}

// TranscriptGT applies the GT predicate on the "transcript" field.
func TranscriptGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldTranscript, v))
}

// TranscriptGTE applies the GTE predicate on the "transcript" field.
func TranscriptGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldTranscript, v))
}

// TranscriptLT applies the LT predicate on the "transcript" field.
func TranscriptLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldTranscript, v))
}

// TranscriptLTE applies the LTE predicate on the "transcript" field.
func TranscriptLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldTranscript, v))
}

// TranscriptContains applies the Contains predicate on the "transcript" field.
func TranscriptContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldTranscript, v))
}

// TranscriptHasPrefix applies the HasPrefix predicate on the "transcript" field.
func TranscriptHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldTranscript, v))
}

// TranscriptHasSuffix applies the HasSuffix predicate on the "transcript" field.
func TranscriptHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldTranscript, v))
}

// TranscriptIsNil applies the IsNil predicate on the "transcript" field.
func TranscriptIsNil() predicate.Record {
	return predicate.Record(sql.FieldIsNull(FieldTranscript))
}

// TranscriptNotNil applies the NotNil predicate on the "transcript" field.
func TranscriptNotNil() predicate.Record {
	return predicate.Record(sql.FieldNotNull(FieldTranscript))
}

// TranscriptEqualFold applies the EqualFold predicate on the "transcript" field.
func TranscriptEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldTranscript, v))
}

// TranscriptContainsFold applies the ContainsFold predicate on the "transcript" field.
func TranscriptContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldTranscript, v))
}

// TranslationTargetLanguageEQ applies the EQ predicate on the "translation_target_language" field.
func TranslationTargetLanguageEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldTranslationTargetLanguage, v))
}

// TranslationTargetLanguageNEQ applies the NEQ predicate on the "translation_target_language" field.
func TranslationTargetLanguageNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldTranslationTargetLanguage, v))
}

// TranslationTargetLanguageIn applies the In predicate on the "translation_target_language" field.
func TranslationTargetLanguageIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldTranslationTargetLanguage, vs...))
}

// TranslationTargetLanguageNotIn applies the NotIn predicate on the "translation_target_language" field.
func TranslationTargetLanguageNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldTranslationTargetLanguage, vs...))
}

// TranslationTargetLanguageGT applies the GT predicate on the "translation_target_language" field.
func TranslationTargetLanguageGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldTranslationTargetLanguage, v))
}

// TranslationTargetLanguageGTE applies the GTE predicate on the "translation_target_language" field.
func TranslationTargetLanguageGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldTranslationTargetLanguage, v))
}

// TranslationTargetLanguageLT applies the LT predicate on the "translation_target_language" field.
func TranslationTargetLanguageLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldTranslationTargetLanguage, v))
}

// TranslationTargetLanguageLTE applies the LTE predicate on the "translation_target_language" field.
func TranslationTargetLanguageLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldTranslationTargetLanguage, v))
}

// TranslationTargetLanguageContains applies the Contains predicate on the "translation_target_language" field.
func TranslationTargetLanguageContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldTranslationTargetLanguage, v))
}

// TranslationTargetLanguageHasPrefix applies the HasPrefix predicate on the "translation_target_language" field.
func TranslationTargetLanguageHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldTranslationTargetLanguage, v))
}

// TranslationTargetLanguageHasSuffix applies the HasSuffix predicate on the "translation_target_language" field.
func TranslationTargetLanguageHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldTranslationTargetLanguage, v))
}

// TranslationTargetLanguageIsNil applies the IsNil predicate on the "translation_target_language" field.
func TranslationTargetLanguageIsNil() predicate.Record {
	return predicate.Record(sql.FieldIsNull(FieldTranslationTargetLanguage))
}

// TranslationTargetLanguageNotNil applies the NotNil predicate on the "translation_target_language" field.
func TranslationTargetLanguageNotNil() predicate.Record {
	return predicate.Record(sql.FieldNotNull(FieldTranslationTargetLanguage))
}

// TranslationTargetLanguageEqualFold applies the EqualFold predicate on the "translation_target_language" field.
func TranslationTargetLanguageEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldTranslationTargetLanguage, v))
}

// TranslationTargetLanguageContainsFold applies the ContainsFold predicate on the "translation_target_language" field.
func TranslationTargetLanguageContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldTranslationTargetLanguage, v))
}

// TranslationEQ applies the EQ predicate on the "translation" field.
func TranslationEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldEQ(FieldTranslation, v))
}

// TranslationNEQ applies the NEQ predicate on the "translation" field.
func TranslationNEQ(v string) predicate.Record {
	return predicate.Record(sql.FieldNEQ(FieldTranslation, v))
}

// TranslationIn applies the In predicate on the "translation" field.
func TranslationIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldIn(FieldTranslation, vs...))
}

// TranslationNotIn applies the NotIn predicate on the "translation" field.
func TranslationNotIn(vs ...string) predicate.Record {
	return predicate.Record(sql.FieldNotIn(FieldTranslation, vs...))
}

// TranslationGT applies the GT predicate on the "translation" field.
func TranslationGT(v string) predicate.Record {
	return predicate.Record(sql.FieldGT(FieldTranslation, v))
}

// TranslationGTE applies the GTE predicate on the "translation" field.
func TranslationGTE(v string) predicate.Record {
	return predicate.Record(sql.FieldGTE(FieldTranslation, v))
}

// TranslationLT applies the LT predicate on the "translation" field.
func TranslationLT(v string) predicate.Record {
	return predicate.Record(sql.FieldLT(FieldTranslation, v))
}

// TranslationLTE applies the LTE predicate on the "translation" field.
func TranslationLTE(v string) predicate.Record {
	return predicate.Record(sql.FieldLTE(FieldTranslation, v))
}

// TranslationContains applies the Contains predicate on the "translation" field.
func TranslationContains(v string) predicate.Record {
	return predicate.Record(sql.FieldContains(FieldTranslation, v))
}

// TranslationHasPrefix applies the HasPrefix predicate on the "translation" field.
func TranslationHasPrefix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasPrefix(FieldTranslation, v))
}

// TranslationHasSuffix applies the HasSuffix predicate on the "translation" field.
func TranslationHasSuffix(v string) predicate.Record {
	return predicate.Record(sql.FieldHasSuffix(FieldTranslation, v))
}

// TranslationIsNil applies the IsNil predicate on the "translation" field.
func TranslationIsNil() predicate.Record {
	return predicate.Record(sql.FieldIsNull(FieldTranslation))
}

// TranslationNotNil applies the NotNil predicate on the "translation" field.
func TranslationNotNil() predicate.Record {
	return predicate.Record(sql.FieldNotNull(FieldTranslation))
}

// TranslationEqualFold applies the EqualFold predicate on the "translation" field.
func TranslationEqualFold(v string) predicate.Record {
	return predicate.Record(sql.FieldEqualFold(FieldTranslation, v))
}

// TranslationContainsFold applies the ContainsFold predicate on the "translation" field.
func TranslationContainsFold(v string) predicate.Record {
	return predicate.Record(sql.FieldContainsFold(FieldTranslation, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Record) predicate.Record {
	return predicate.Record(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Record) predicate.Record {
	return predicate.Record(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Record) predicate.Record {
	return predicate.Record(sql.NotPredicates(p))
}
