// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RecordsColumns holds the columns for the "records" table.
	RecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "video_url", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "video_id", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "file_location", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"downloaded"}},
	}
	// RecordsTable holds the schema information for the "records" table.
	RecordsTable = &schema.Table{
		Name:       "records",
		Columns:    RecordsColumns,
		PrimaryKey: []*schema.Column{RecordsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RecordsTable,
	}
)

func init() {
}
