// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/GrewalAS/yt-transcription-translation/ent/predicate"
	"github.com/GrewalAS/yt-transcription-translation/ent/record"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeRecord = "Record"
)

// RecordMutation represents an operation that mutates the Record nodes in the graph.
type RecordMutation struct {
	config
	op                          Op
	typ                         string
	id                          *int
	video_url                   *string
	video_id                    *string
	original_language           *string
	status                      *record.Status
	file_location               *string
	run_id                      *uuid.UUID
	transcript                  *string
	translation_target_language *string
	translation                 *string
	clearedFields               map[string]struct{}
	done                        bool
	oldValue                    func(context.Context) (*Record, error)
	predicates                  []predicate.Record
}

var _ ent.Mutation = (*RecordMutation)(nil)

// recordOption allows management of the mutation configuration using functional options.
type recordOption func(*RecordMutation)

// newRecordMutation creates new mutation for the Record entity.
func newRecordMutation(c config, op Op, opts ...recordOption) *RecordMutation {
	m := &RecordMutation{
		config:        c,
		op:            op,
		typ:           TypeRecord,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRecordID sets the ID field of the mutation.
func withRecordID(id int) recordOption {
	return func(m *RecordMutation) {
		var (
			err   error
			once  sync.Once
			value *Record
		)
		m.oldValue = func(ctx context.Context) (*Record, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Record.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRecord sets the old Record of the mutation.
func withRecord(node *Record) recordOption {
	return func(m *RecordMutation) {
		m.oldValue = func(context.Context) (*Record, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RecordMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RecordMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RecordMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RecordMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Record.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetVideoURL sets the "video_url" field.
func (m *RecordMutation) SetVideoURL(s string) {
	m.video_url = &s
}

// VideoURL returns the value of the "video_url" field in the mutation.
func (m *RecordMutation) VideoURL() (r string, exists bool) {
	v := m.video_url
	if v == nil {
		return
	}
	return *v, true
}

// OldVideoURL returns the old "video_url" field's value of the Record entity.
// If the Record object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RecordMutation) OldVideoURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVideoURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVideoURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVideoURL: %w", err)
	}
	return oldValue.VideoURL, nil
}

// ResetVideoURL resets all changes to the "video_url" field.
func (m *RecordMutation) ResetVideoURL() {
	m.video_url = nil
}

// SetVideoID sets the "video_id" field.
func (m *RecordMutation) SetVideoID(s string) {
	m.video_id = &s
}

// VideoID returns the value of the "video_id" field in the mutation.
func (m *RecordMutation) VideoID() (r string, exists bool) {
	v := m.video_id
	if v == nil {
		return
	}
	return *v, true
}

// OldVideoID returns the old "video_id" field's value of the Record entity.
// If the Record object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RecordMutation) OldVideoID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVideoID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVideoID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVideoID: %w", err)
	}
	return oldValue.VideoID, nil
}

// ResetVideoID resets all changes to the "video_id" field.
func (m *RecordMutation) ResetVideoID() {
	m.video_id = nil
}

// SetOriginalLanguage sets the "original_language" field.
func (m *RecordMutation) SetOriginalLanguage(s string) {
	m.original_language = &s
}

// OriginalLanguage returns the value of the "original_language" field in the mutation.
func (m *RecordMutation) OriginalLanguage() (r string, exists bool) {
	v := m.original_language
	if v == nil {
		return
	}
	return *v, true
}

// OldOriginalLanguage returns the old "original_language" field's value of the Record entity.
// If the Record object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RecordMutation) OldOriginalLanguage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOriginalLanguage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOriginalLanguage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOriginalLanguage: %w", err)
	}
	return oldValue.OriginalLanguage, nil
}

// ResetOriginalLanguage resets all changes to the "original_language" field.
func (m *RecordMutation) ResetOriginalLanguage() {
	m.original_language = nil
}

// SetStatus sets the "status" field.
func (m *RecordMutation) SetStatus(r record.Status) {
	m.status = &r
}

// Status returns the value of the "status" field in the mutation.
func (m *RecordMutation) Status() (r record.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Record entity.
// If the Record object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RecordMutation) OldStatus(ctx context.Context) (v record.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *RecordMutation) ResetStatus() {
	m.status = nil
}

// SetFileLocation sets the "file_location" field.
func (m *RecordMutation) SetFileLocation(s string) {
	m.file_location = &s
}

// FileLocation returns the value of the "file_location" field in the mutation.
func (m *RecordMutation) FileLocation() (r string, exists bool) {
	v := m.file_location
	if v == nil {
		return
	}
	return *v, true
}

// OldFileLocation returns the old "file_location" field's value of the Record entity.
// If the Record object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RecordMutation) OldFileLocation(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFileLocation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFileLocation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFileLocation: %w", err)
	}
	return oldValue.FileLocation, nil
}

// ClearFileLocation clears the value of the "file_location" field.
func (m *RecordMutation) ClearFileLocation() {
	m.file_location = nil
	m.clearedFields[record.FieldFileLocation] = struct{}{}
}

// FileLocationCleared returns if the "file_location" field was cleared in this mutation.
func (m *RecordMutation) FileLocationCleared() bool {
	_, ok := m.clearedFields[record.FieldFileLocation]
	return ok
}

// ResetFileLocation resets all changes to the "file_location" field.
func (m *RecordMutation) ResetFileLocation() {
	m.file_location = nil
	delete(m.clearedFields, record.FieldFileLocation)
}

// SetRunID sets the "run_id" field.
func (m *RecordMutation) SetRunID(u uuid.UUID) {
	m.run_id = &u
}

// RunID returns the value of the "run_id" field in the mutation.
func (m *RecordMutation) RunID() (r uuid.UUID, exists bool) {
	v := m.run_id
	if v == nil {
		return
	}
	return *v, true
}

// OldRunID returns the old "run_id" field's value of the Record entity.
// If the Record object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RecordMutation) OldRunID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRunID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRunID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRunID: %w", err)
	}
	return oldValue.RunID, nil
}

// ClearRunID clears the value of the "run_id" field.
func (m *RecordMutation) ClearRunID() {
	m.run_id = nil
	m.clearedFields[record.FieldRunID] = struct{}{}
}

// RunIDCleared returns if the "run_id" field was cleared in this mutation.
func (m *RecordMutation) RunIDCleared() bool {
	_, ok := m.clearedFields[record.FieldRunID]
	return ok
}

// ResetRunID resets all changes to the "run_id" field.
func (m *RecordMutation) ResetRunID() {
	m.run_id = nil
	delete(m.clearedFields, record.FieldRunID)
}

// SetTranscript sets the "transcript" field.
func (m *RecordMutation) SetTranscript(s string) {
	m.transcript = &s
}

// Transcript returns the value of the "transcript" field in the mutation.
func (m *RecordMutation) Transcript() (r string, exists bool) {
	v := m.transcript
	if v == nil {
		return
	}
	return *v, true
}

// OldTranscript returns the old "transcript" field's value of the Record entity.
// If the Record object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RecordMutation) OldTranscript(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTranscript is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTranscript requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTranscript: %w", err)
	}
	return oldValue.Transcript, nil
}

// ClearTranscript clears the value of the "transcript" field.
func (m *RecordMutation) ClearTranscript() {
	m.transcript = nil
	m.clearedFields[record.FieldTranscript] = struct{}{}
}

// TranscriptCleared returns if the "transcript" field was cleared in this mutation.
func (m *RecordMutation) TranscriptCleared() bool {
	_, ok := m.clearedFields[record.FieldTranscript]
	return ok
}

// ResetTranscript resets all changes to the "transcript" field.
func (m *RecordMutation) ResetTranscript() {
	m.transcript = nil
	delete(m.clearedFields, record.FieldTranscript)
}

// SetTranslationTargetLanguage sets the "translation_target_language" field.
func (m *RecordMutation) SetTranslationTargetLanguage(s string) {
	m.translation_target_language = &s
}

// TranslationTargetLanguage returns the value of the "translation_target_language" field in the mutation.
func (m *RecordMutation) TranslationTargetLanguage() (r string, exists bool) {
	v := m.translation_target_language
	if v == nil {
		return
	}
	return *v, true
}

// OldTranslationTargetLanguage returns the old "translation_target_language" field's value of the Record entity.
// If the Record object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RecordMutation) OldTranslationTargetLanguage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTranslationTargetLanguage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTranslationTargetLanguage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTranslationTargetLanguage: %w", err)
	}
	return oldValue.TranslationTargetLanguage, nil
}

// ClearTranslationTargetLanguage clears the value of the "translation_target_language" field.
func (m *RecordMutation) ClearTranslationTargetLanguage() {
	m.translation_target_language = nil
	m.clearedFields[record.FieldTranslationTargetLanguage] = struct{}{}
}

// TranslationTargetLanguageCleared returns if the "translation_target_language" field was cleared in this mutation.
func (m *RecordMutation) TranslationTargetLanguageCleared() bool {
	_, ok := m.clearedFields[record.FieldTranslationTargetLanguage]
	return ok
}

// ResetTranslationTargetLanguage resets all changes to the "translation_target_language" field.
func (m *RecordMutation) ResetTranslationTargetLanguage() {
	m.translation_target_language = nil
	delete(m.clearedFields, record.FieldTranslationTargetLanguage)
}

// SetTranslation sets the "translation" field.
func (m *RecordMutation) SetTranslation(s string) {
	m.translation = &s
}

// Translation returns the value of the "translation" field in the mutation.
func (m *RecordMutation) Translation() (r string, exists bool) {
	v := m.translation
	if v == nil {
		return
	}
	return *v, true
}

// OldTranslation returns the old "translation" field's value of the Record entity.
// If the Record object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RecordMutation) OldTranslation(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTranslation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTranslation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTranslation: %w", err)
	}
	return oldValue.Translation, nil
}

// ClearTranslation clears the value of the "translation" field.
func (m *RecordMutation) ClearTranslation() {
	m.translation = nil
	m.clearedFields[record.FieldTranslation] = struct{}{}
}

// TranslationCleared returns if the "translation" field was cleared in this mutation.
func (m *RecordMutation) TranslationCleared() bool {
	_, ok := m.clearedFields[record.FieldTranslation]
	return ok
}

// ResetTranslation resets all changes to the "translation" field.
func (m *RecordMutation) ResetTranslation() {
	m.translation = nil
	delete(m.clearedFields, record.FieldTranslation)
}

// Where appends a list predicates to the RecordMutation builder.
func (m *RecordMutation) Where(ps ...predicate.Record) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RecordMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RecordMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Record, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RecordMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RecordMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Record).
func (m *RecordMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RecordMutation) Fields() []string {
	fields := make([]string, 0, 9)
	if m.video_url != nil {
		fields = append(fields, record.FieldVideoURL)
	}
	if m.video_id != nil {
		fields = append(fields, record.FieldVideoID)
	}
	if m.original_language != nil {
		fields = append(fields, record.FieldOriginalLanguage)
	}
	if m.status != nil {
		fields = append(fields, record.FieldStatus)
	}
	if m.file_location != nil {
		fields = append(fields, record.FieldFileLocation)
	}
	if m.run_id != nil {
		fields = append(fields, record.FieldRunID)
	}
	if m.transcript != nil {
		fields = append(fields, record.FieldTranscript)
	}
	if m.translation_target_language != nil {
		fields = append(fields, record.FieldTranslationTargetLanguage)
	}
	if m.translation != nil {
		fields = append(fields, record.FieldTranslation)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RecordMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case record.FieldVideoURL:
		return m.VideoURL()
	case record.FieldVideoID:
		return m.VideoID()
	case record.FieldOriginalLanguage:
		return m.OriginalLanguage()
	case record.FieldStatus:
		return m.Status()
	case record.FieldFileLocation:
		return m.FileLocation()
	case record.FieldRunID:
		return m.RunID()
	case record.FieldTranscript:
		return m.Transcript()
	case record.FieldTranslationTargetLanguage:
		return m.TranslationTargetLanguage()
	case record.FieldTranslation:
		return m.Translation()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RecordMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case record.FieldVideoURL:
		return m.OldVideoURL(ctx)
	case record.FieldVideoID:
		return m.OldVideoID(ctx)
	case record.FieldOriginalLanguage:
		return m.OldOriginalLanguage(ctx)
	case record.FieldStatus:
		return m.OldStatus(ctx)
	case record.FieldFileLocation:
		return m.OldFileLocation(ctx)
	case record.FieldRunID:
		return m.OldRunID(ctx)
	case record.FieldTranscript:
		return m.OldTranscript(ctx)
	case record.FieldTranslationTargetLanguage:
		return m.OldTranslationTargetLanguage(ctx)
	case record.FieldTranslation:
		return m.OldTranslation(ctx)
	}
	return nil, fmt.Errorf("unknown Record field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RecordMutation) SetField(name string, value ent.Value) error {
	switch name {
	case record.FieldVideoURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVideoURL(v)
		return nil
	case record.FieldVideoID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVideoID(v)
		return nil
	case record.FieldOriginalLanguage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOriginalLanguage(v)
		return nil
	case record.FieldStatus:
		v, ok := value.(record.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case record.FieldFileLocation:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFileLocation(v)
		return nil
	case record.FieldRunID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRunID(v)
		return nil
	case record.FieldTranscript:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTranscript(v)
		return nil
	case record.FieldTranslationTargetLanguage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTranslationTargetLanguage(v)
		return nil
	case record.FieldTranslation:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTranslation(v)
		return nil
	}
	return fmt.Errorf("unknown Record field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RecordMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RecordMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RecordMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Record numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RecordMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(record.FieldFileLocation) {
		fields = append(fields, record.FieldFileLocation)
	}
	if m.FieldCleared(record.FieldRunID) {
		fields = append(fields, record.FieldRunID)
	}
	if m.FieldCleared(record.FieldTranscript) {
		fields = append(fields, record.FieldTranscript)
	}
	if m.FieldCleared(record.FieldTranslationTargetLanguage) {
		fields = append(fields, record.FieldTranslationTargetLanguage)
	}
	if m.FieldCleared(record.FieldTranslation) {
		fields = append(fields, record.FieldTranslation)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RecordMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RecordMutation) ClearField(name string) error {
	switch name {
	case record.FieldFileLocation:
		m.ClearFileLocation()
		return nil
	case record.FieldRunID:
		m.ClearRunID()
		return nil
	case record.FieldTranscript:
		m.ClearTranscript()
		return nil
	case record.FieldTranslationTargetLanguage:
		m.ClearTranslationTargetLanguage()
		return nil
	case record.FieldTranslation:
		m.ClearTranslation()
		return nil
	}
	return fmt.Errorf("unknown Record nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RecordMutation) ResetField(name string) error {
	switch name {
	case record.FieldVideoURL:
		m.ResetVideoURL()
		return nil
	case record.FieldVideoID:
		m.ResetVideoID()
		return nil
	case record.FieldOriginalLanguage:
		m.ResetOriginalLanguage()
		return nil
	case record.FieldStatus:
		m.ResetStatus()
		return nil
	case record.FieldFileLocation:
		m.ResetFileLocation()
		return nil
	case record.FieldRunID:
		m.ResetRunID()
		return nil
	case record.FieldTranscript:
		m.ResetTranscript()
		return nil
	case record.FieldTranslationTargetLanguage:
		m.ResetTranslationTargetLanguage()
		return nil
	case record.FieldTranslation:
		m.ResetTranslation()
		return nil
	}
	return fmt.Errorf("unknown Record field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RecordMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RecordMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RecordMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RecordMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RecordMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RecordMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RecordMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Record unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RecordMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Record edge %s", name)
}
