// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/GrewalAS/yt-transcription-translation/ent/record"
	"github.com/GrewalAS/yt-transcription-translation/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	recordFields := schema.Record{}.Fields()
	_ = recordFields
	// recordDescVideoURL is the schema descriptor for video_url field.
	recordDescVideoURL := recordFields[0].Descriptor()
	// record.VideoURLValidator is a validator for the "video_url" field. It is called by the builders before save.
	record.VideoURLValidator = recordDescVideoURL.Validators[0].(func(string) error)
	// recordDescVideoID is the schema descriptor for video_id field.
	recordDescVideoID := recordFields[1].Descriptor()
	// record.VideoIDValidator is a validator for the "video_id" field. It is called by the builders before save.
	record.VideoIDValidator = recordDescVideoID.Validators[0].(func(string) error)
	// recordDescFileLocation is the schema descriptor for file_location field.
	recordDescFileLocation := recordFields[2].Descriptor()
	// record.FileLocationValidator is a validator for the "file_location" field. It is called by the builders before save.
	record.FileLocationValidator = recordDescFileLocation.Validators[0].(func(string) error)
}
